import fs from 'fs/promises';
import path from 'path';
import { SYSTEM_CONFIG } from '../config/system-config.js';

class FileManager {
  constructor() {
    this.outputDir = SYSTEM_CONFIG.outputDir;
  }

  async ensureDirectory(dirPath) {
    try {
      await fs.mkdir(dirPath, { recursive: true });
      return true;
    } catch (error) {
      throw new Error(`Failed to create directory ${dirPath}: ${error.message}`);
    }
  }

  async projectExists(projectName) {
    const projectPath = path.join(this.outputDir, projectName);
    try {
      await fs.access(projectPath);
      return true;
    } catch {
      return false;
    }
  }

  async createProject(projectName) {
    const projectPath = path.join(this.outputDir, projectName);

    if (await this.projectExists(projectName)) {
      throw new Error(`Project ${projectName} already exists`);
    }

    await this.ensureDirectory(projectPath);
    return projectPath;
  }

  async writeFile(projectPath, filePath, content) {
    const fullPath = path.join(projectPath, filePath);
    const dirPath = path.dirname(fullPath);

    // Ensure directory exists
    await this.ensureDirectory(dirPath);

    // Write file
    try {
      await fs.writeFile(fullPath, content, 'utf-8');
      return fullPath;
    } catch (error) {
      throw new Error(`Failed to write file ${fullPath}: ${error.message}`);
    }
  }

  async createPackageJson(projectPath, dependencies = []) {
    const packageJson = {
      name: path.basename(projectPath),
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "next lint"
      },
      dependencies: {
        react: "^18",
        "react-dom": "^18",
        next: "14.1.0"
      },
      devDependencies: {
        typescript: "^5",
        "@types/node": "^20",
        "@types/react": "^18",
        "@types/react-dom": "^18",
        autoprefixer: "^10.0.1",
        postcss: "^8",
        tailwindcss: "^3.3.0",
        eslint: "^8",
        "eslint-config-next": "14.1.0"
      }
    };

    // Add custom dependencies
    dependencies.forEach(dep => {
      if (typeof dep === 'string') {
        packageJson.dependencies[dep] = 'latest';
      } else if (dep.name && dep.version) {
        packageJson.dependencies[dep.name] = dep.version;
      }
    });

    const content = JSON.stringify(packageJson, null, 2);
    await this.writeFile(projectPath, 'package.json', content);
  }

  async createGitignore(projectPath) {
    const content = `# dependencies
node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env*.local
.env

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts
`;
    await this.writeFile(projectPath, '.gitignore', content);
  }

  async createTailwindConfig(projectPath) {
    const content = `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
`;
    await this.writeFile(projectPath, 'tailwind.config.js', content);
  }

  async createPostcssConfig(projectPath) {
    const content = `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`;
    await this.writeFile(projectPath, 'postcss.config.js', content);
  }

  async createNextConfig(projectPath) {
    const content = `/** @type {import('next').NextConfig} */
const nextConfig = {}

module.exports = nextConfig
`;
    await this.writeFile(projectPath, 'next.config.js', content);
  }

  async createTsConfig(projectPath) {
    const content = `{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`;
    await this.writeFile(projectPath, 'tsconfig.json', content);
  }

  async createGlobalsCss(projectPath) {
    const content = `@tailwind base;
@tailwind components;
@tailwind utilities;
`;
    await this.writeFile(projectPath, 'app/globals.css', content);
  }

  async createRootLayout(projectPath) {
    const content = `import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next.js App',
  description: 'Generated by Next.js Agent System',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
`;
    await this.writeFile(projectPath, 'app/layout.tsx', content);
  }

  async setupProjectBoilerplate(projectPath, dependencies = []) {
    await this.createPackageJson(projectPath, dependencies);
    await this.createGitignore(projectPath);
    await this.createTailwindConfig(projectPath);
    await this.createPostcssConfig(projectPath);
    await this.createNextConfig(projectPath);
    await this.createTsConfig(projectPath);
    await this.createGlobalsCss(projectPath);
    await this.createRootLayout(projectPath);
  }

  async readFile(filePath) {
    try {
      return await fs.readFile(filePath, 'utf-8');
    } catch (error) {
      throw new Error(`Failed to read file ${filePath}: ${error.message}`);
    }
  }

  async fileExists(filePath) {
    try {
      await fs.access(filePath);
      return true;
    } catch {
      return false;
    }
  }
}

export default new FileManager();
